version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w -X github.com/nchatzak/envprobe/cmd.version={{ .Version }}

archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  abbrev: -1
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - '^chore\(deps\):'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Dependency updates
      regexp: '^chore\(deps\):'
      order: 2
